# -*- coding: utf-8 -*-

from sdl2 import *

class GameVars:
    
    TITLE = "PyTank 1990"
    WIDTH = 256
    HEIGHT = 240
    DELAY = 10

    BUTTON_LEFT = SDLK_LEFT
    BUTTON_RIGHT = SDLK_RIGHT
    BUTTON_UP = SDLK_UP
    BUTTON_DOWN = SDLK_DOWN
    
    BUTTON_START = SDLK_RETURN
    BUTTON_SELECT = SDLK_s
    BUTTON_A = SDLK_a
    BUTTON_B = SDLK_z
    
    FRAME_WIDTH = 16        
    CURSOR_GRID_WIDTH = 16
    LEVEL_GRID_WIDTH = 8
    
    NUM_CURSOR_GRID_X = (WIDTH - FRAME_WIDTH * 3) / CURSOR_GRID_WIDTH
    NUM_CURSOR_GRID_Y = (HEIGHT - FRAME_WIDTH * 2) / CURSOR_GRID_WIDTH
    NUM_GRID_X = NUM_CURSOR_GRID_X * 2
    NUM_GRID_Y = NUM_CURSOR_GRID_Y * 2
        